# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        # the name of the "filter set"
        product_thumb:
            # adjust the image quality to 75%
            quality: 75
            filters:
                # create a thumbnail: set size to 360x230 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [ 360, 230 ], mode: outbound }
        product_table_thumb:
            # adjust the image quality to 75%
            quality: 75
            filters:
                # create a thumbnail: set size to 64x64 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [ 64, 64 ], mode: outbound }
        category_thumb:
            # adjust the image quality to 75%
            quality: 75
            filters:
                # create a thumbnail: set size to 360x230 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [ 360, 230 ], mode: outbound }