twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes: [ 'bootstrap_4_layout.html.twig' ]
  date:
    timezone: Europe/Paris

  paths:
    '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator

