vich_uploader:
  db_driver: orm

  mappings:
    products_image:
      uri_prefix: /upload/products
      upload_destination: '%kernel.project_dir%/public/upload/products'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    users_avatar:
      uri_prefix: /upload/users
      upload_destination: '%kernel.project_dir%/public/upload/users'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true